name: Trigger lint format

on:
  workflow_call:
    secrets:
      MLKIT_BRANCH_TOKEN:
        required: true
        description: "Token to access mlkit-branch account"
    inputs:
      COMMIT_MESSAGE:
        description: "Commit message to prevent re-triggering the workflow"
        required: false
        type: string
        default: "🤖 Lint code"

permissions:
  contents: write

jobs:
  format-code:
    name: Trigger lint bot
    uses: khulnasoft/workflows/.github/workflows/lint-bot.yml@automatic-lint-pr
    secrets: inherit
