name: Trigger lint format
on:
  workflow_call:
    secrets:
      MLKIT_BRANCH_TOKEN:
        required: true
        description: "Token to access mlkit-branch account"

permissions:
  contents: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Check for triggers
    if: ${{ github.event.issue.pull_request }}
    outputs:
      mlkit-gardener: ${{ steps.mlkit-gardener.outputs.triggered && steps.mlkit-gardener.outputs.comment_body == 'mlkit-gardener' }}
      head-ref: ${{ steps.comment-branch.outputs.head_ref }}
      head-repo: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: mlkit-gardener
        name: Check for mlkit-lint
        with:
          trigger: 'mlkit-gardener'

      - name: Mark comment as read
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ steps.mlkit-gardener.outputs.triggered && steps.mlkit-gardener.outputs.comment_body == 'mlkit-gardener'}}
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: 'rocket'
          token: ${{ secrets.MLKIT_BRANCH_TOKEN }}
      
      - uses: KareemMAX/pull-request-comment-branch@head-repo-owner-release
        id: comment-branch
        if: ${{ steps.mlkit-gardener.outputs.triggered && steps.mlkit-gardener.outputs.comment_body == 'mlkit-gardener'}}

  format-code:
    needs: trigger
    if: ${{ needs.trigger.outputs.mlkit-gardener == 'true' }}
    name: Trigger lint bot
    uses: ./.github/workflows/lint-bot.yml
    secrets: inherit
    with:
      head-ref: ${{ needs.trigger.outputs.head-ref }}
      head-repo: ${{ needs.trigger.outputs.head-repo }}
      only-changed-files: true

  acknowledge-format:
    runs-on: ubuntu-latest
    needs: format-code
    name: Acknowledge lint bot
    steps:
      - name: Acknowledge lint bot
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            :white_check_mark: Ivy gardener has formatted your code.
            If changes are requested, don't forget to pull your fork.
          reactions: '+1'
          reactions-edit-mode: replace
          token: ${{ secrets.MLKIT_BRANCH_TOKEN }}

  format-code-failed:
    runs-on: ubuntu-latest
    needs: format-code
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    name: Acknowledge lint bot
    steps:
      - name: Acknowledge lint bot
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            :x: Ivy gardener failed to format your code.
          reactions: '-1'
          reactions-edit-mode: replace
          token: ${{ secrets.MLKIT_BRANCH_TOKEN }}
