run-name: Publish ${{ inputs.version }} docs
on: 
  workflow_call:
      secrets:
        SSH_GH_PAGES:
          description: 'SSH key for GitHub Pages deployment'
          required: true
      inputs:
        version:
          description: 'Version of the docs'
          required: false
          default: 'dev'
          type: string
        package-dependencies:
          description: 'Apt package dependencies'
          required: false
          default: ''
          type: string
        repo_name:
          description: 'Repository Name'
          required: true
          default: ''
          type: string
        

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    name: Publish ${{ inputs.version }} docs
    steps:
      - name: Checkout 🛎️ ${{ inputs.repo_name }}
        uses: actions/checkout@v3
        with:
          repository: khulnasoft/${{ inputs.repo_name }}
          fetch-depth: 1

      - name: Checkout 🛎️ Doc-builder
        uses: actions/checkout@v3
        with:
          repository: khulnasoft/doc-builder
          path: .doc-builder

      - name: Install apt dependencies
        if: inputs.package-dependencies != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.package-dependencies }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Get cache week key
        id: get-cache-week-key
        run: |
          echo "week-key=$(date +'%Y-%V')" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./.venv
          key: ${{ runner.os }}-pip-${{ steps.get-cache-week-key.outputs.week-key }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create virtual environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv

      - name: Build docs
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install wheel setuptools
          cd .doc-builder
          export IVY_VERSION=${{ inputs.version }}
          ./make_docs_without_docker.sh ..

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: docs/build
          target-folder: "${{ inputs.version != 'dev' && format('{0}/', inputs.version) || '' }}${{ inputs.repo_name }}"
          ssh-key: ${{ secrets.SSH_GH_PAGES }}
          branch: main
          git-config-name: mlkit-seed
          git-config-email: infosulaimanbd@gmail.com
          repository-name: khulnasoft/docs
          clean: true
